name       : qt5-serialport
version    : 5.6.2
release    : 1
source     :
    - http://download.qt.io/official_releases/qt/5.6/5.6.2/submodules/qtserialport-opensource-src-5.6.2.tar.xz : af76281bad2c2bd283189635316b46091f6712134b845ae1b9e3016eec94f376
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Serial Port Module
description: |
    Qt Serial Port provides the basic functionality, which includes configuring, I/O operations, getting and setting the control signals of the RS-232 pinouts.
    The following items are not supported by this module:
    - Terminal features, such as echo, control CR/LF, and so on.
    - Text mode.
    - Configuring timeouts and delays while reading or writing.
    - Pinout signal change notification.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos :
        /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialport.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
