name       : qt5-serialport
version    : 5.15.2
release    : 21
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtserialport-everywhere-src-5.15.2.tar.xz : 59c559d748417306bc1b2cf2315c1e63eed011ace38ad92946af71f23e2ef79d
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Serial Port Module
description: |
    Qt Serial Port provides the basic functionality, which includes configuring, I/O operations, getting and setting the control signals of the RS-232 pinouts.
    The following items are not supported by this module:
    - Terminal features, such as echo, control CR/LF, and so on.
    - Text mode.
    - Configuring timeouts and delays while reading or writing.
    - Pinout signal change notification.
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialport.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
