name       : qt5-serialport
version    : 5.9.0
release    : 2
source     :
    - http://download.qt.io/official_releases/qt/5.9/5.9.0/submodules//qtserialport-opensource-src-5.9.0.tar.xz : 80022e3e6d5652502891fec3774615a36d51901dacc4fbb2dfe6e562fd729d7f
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Serial Port Module
description: |
    Qt Serial Port provides the basic functionality, which includes configuring, I/O operations, getting and setting the control signals of the RS-232 pinouts.
    The following items are not supported by this module:
    - Terminal features, such as echo, control CR/LF, and so on.
    - Text mode.
    - Configuring timeouts and delays while reading or writing.
    - Pinout signal change notification.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialport.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
